// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using api.Database;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(ApplicationDB))]
    [Migration("20250307182649_CreateTableUserAndVoucher")]
    partial class CreateTableUserAndVoucher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("api.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("VARCHAR(36)")
                        .HasColumnName("user_id");

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("address");

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("BLOB")
                        .HasColumnName("avatar");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("email");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("VARCHAR(60)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_gender", "gender IN ('male','female','other')");

                            t.HasCheckConstraint("ck_phone_and_email", "phone IS NOT NULL OR email IS NOT NULL");

                            t.HasCheckConstraint("ck_users_email", "email IS NULL OR email REGEXP '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$'");

                            t.HasCheckConstraint("ck_users_phone", "phone IS NULL OR phone REGEXP '^[0-9]{10}$'");

                            t.HasCheckConstraint("ck_users_role", "role IN ('admin', 'user')");
                        });
                });

            modelBuilder.Entity("api.Models.Voucher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("voucher_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("VARCHAR(50)")
                        .HasColumnName("code");

                    b.Property<decimal?>("DiscountAmount")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("discount_amount");

                    b.Property<decimal?>("DiscountPercentage")
                        .HasColumnType("DECIMAL(5, 2)")
                        .HasColumnName("discount_percentage");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("DATE")
                        .HasColumnName("end_date");

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("max_discount_amount");

                    b.Property<int?>("MaxUses")
                        .HasColumnType("INT")
                        .HasColumnName("max_uses");

                    b.Property<decimal?>("MinOrderValue")
                        .HasColumnType("DECIMAL(10, 2)")
                        .HasColumnName("min_order_value");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("DATE")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("VARCHAR(10)")
                        .HasColumnName("status");

                    b.Property<int>("UsedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasDefaultValue(0)
                        .HasColumnName("used_count");

                    b.HasKey("Id");

                    b.ToTable("vouchers", null, t =>
                        {
                            t.HasCheckConstraint("ck_vouchers_dates", "start_date <= end_date");

                            t.HasCheckConstraint("ck_vouchers_discount", "discount_percentage IS NOT NULL OR discount_amount IS NOT NULL");

                            t.HasCheckConstraint("ck_vouchers_max_uses", "max_uses IS NULL OR max_uses >= used_count");

                            t.HasCheckConstraint("ck_vouchers_status", "status IN ('active', 'inactive')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
